Repository null-channel/eddington, pull requests merged in 2023-06, with the labels that each got.

#6 adding the login page
  ui/src/assets/img/sign-up.png
  ui/src/core/routers/index.ts
  ui/src/formkit.config.ts
  ui/src/index.css
  ui/src/pages/Home/home.html
  ui/src/pages/Home/home.vue
  ui/src/pages/Sign-up/sign-up.css
  ui/src/pages/Sign-up/sign-up.html
  ui/src/pages/Sign-up/sign-up.vue
  ui/src/shared/components/header/header.html
  ui/src/shared/components/hero-section/heroSection.html
  ui/src/shared/components/hero-section/heroSection.vue
  ui/src/shared/components/null-cloud-title/nullCloudTitle.html
  ui/src/shared/components/null-cloud-title/nullCloudTitle.vue
  ui/tailwind.config.js
Labels: enhancement

#10 Init marketing Api
  .gitignore
  api/.gitignore
  api/eddington.postman_collection.json
  api/go.mod
  api/go.sum
  api/main.go
  api/marketing/controllers/marketing.go
  deployments/manifests/nats/kustomization.yaml
Labels: enhancement, backend

#9 Feat/GitHub watcher
  github-watcher/go.mod
  github-watcher/go.sum
  github-watcher/main.go
  go.work
  proto/github-watcher/watchRepo.pb.go
  proto/github-watcher/watchRepo.proto
  proto/github-watcher/watchRepo_grpc.pb.go
Labels: enhancement

#16 fix error handling for wrong cridentials
  ui/src/core/helpers/ory-error-handler.helper.ts
  ui/src/shared/components/flow/login/login-flow.vue
Labels: bug, frontend

#15 adding sub button api connection
  ui/src/shared/components/hero-section/heroSection.html
  ui/src/shared/components/hero-section/heroSection.vue
Labels: enhancement, frontend
